/**
 * @file clap_i18n.h
 * @brief Internationalization support for libclap
 *
 * Provides a callback-based translation system for all user-facing
 * strings (help text, error messages, usage output, etc.).
 *
 * By default no translator is set and all output is in English.
 * Call clap_set_translator() to install a custom translation function.
 *
 * ## Finding all translatable strings
 *
 * A complete list of all message IDs is available in the PO template.
 * Depending on how you obtained libclap:
 *
 *   - **Building from source**:  po/libclap.pot
 *   - **Installed via package**:  $(prefix)/share/libclap/libclap.pot
 *     (e.g. /usr/share/libclap/libclap.pot)
 *
 * This file is generated by xgettext and contains every English string
 * that the library can translate, organized by source file location.
 * Use it as the starting point for creating translation files:
 *
 *     msginit -l zh_CN.UTF-8 -o zh_CN.po -i /path/to/libclap.pot
 *     # edit zh_CN.po, then:
 *     msgfmt -o zh_CN.mo zh_CN.po
 *
 * To regenerate the template after modifying library source:
 *
 *     cmake --build build --target pot
 *
 * Alternatively, call clap_set_translator() with a custom lookup
 * function that enumerates the messages you want to translate.
 */

#ifndef CLAP_I18N_H
#define CLAP_I18N_H

#include <clap/clap_types.h>
#include <clap/clap_export.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Translation callback.
 *
 * Given an English message ID (@p msgid), returns the translated string.
 * The returned pointer must remain valid for the lifetime of the caller's
 * use (typically the immediately surrounding fprintf / clap_error_set
 * call).  Returning @p msgid directly is the correct fallback when no
 * translation is available.
 *
 * @param msgid     English source string (NUL-terminated).
 * @param user_data Opaque pointer passed to clap_set_translator().
 * @return Translated string, or @p msgid if no translation available.
 */
typedef const char* (*clap_translate_func)(const char *msgid, void *user_data);

/**
 * @brief Set the global message translator.
 *
 * Once set, all help text, error messages, usage output, deprecation
 * warnings, and version strings produced by the library pass through
 * the translator before being emitted.
 *
 * Must be called before any parsing begins.  Like clap_set_allocator(),
 * the translator can only be set once — subsequent calls are ignored.
 *
 * @param translator Translation callback, or NULL to clear/disable.
 * @param user_data  Opaque pointer passed to @p translator on each call.
 */
CLAP_EXPORT void clap_set_translator(clap_translate_func translator, void *user_data);

#ifdef __cplusplus
}
#endif

#endif /* CLAP_I18N_H */
